/**
 * @file trace_arti.h
 * @brief Platform Extension API – apext::log::TraceArti base template.
 *
 * AUTOSAR Adaptive Platform R25-11
 * Document ID 853  – Appendix C
 *
 * Traceability:
 *   [SWS_LOG_00255]  SetThreshold
 *   C.1.1.1.1        TraceArti base template (no-op; specialisations generated
 *                    by the trace-tool vendor code generator)
 *
 * The base template is a no-op.  Trace-tool vendors generate specialisations
 * of this function template in a file named trace_arti_spec.h, located
 * alongside the generated modelled message headers.
 *
 * Coding standards:
 *   - MISRA C++:2023 Rule 14.3.2 – explicit template instantiation permitted
 *   - CERT C++ DCL51-CPP         – reserved names not used
 *   - ISO/SAE 21434              – no UB in template specialisations
 */

#ifndef APEXT_LOG_TRACE_ARTI_H_
#define APEXT_LOG_TRACE_ARTI_H_

namespace apext {
namespace log {

/**
 * @brief Base (no-op) TraceArti function template.
 *
 * Specialisations generated by the trace-tool vendor replace this no-op
 * for messages that are configured to be traced to ARTI.
 *
 * @tparam MsgId   Implementation-defined message identity type.
 * @tparam Params  Types of message parameters.
 * @param msg_id   Message identity object.
 * @param params   Message parameters (ignored in the base template).
 */
template <typename MsgId, typename... Params>
void TraceArti(const MsgId & /*msg_id*/,
               const Params &... /*params*/) noexcept
{
    // Base template is intentionally empty (no-op).
    // Trace-tool vendor must provide specialisations via trace_arti_spec.h.
}

} // namespace log
} // namespace apext

#endif // APEXT_LOG_TRACE_ARTI_H_
